application:
  description: '@project.description@'
  name: '@project.artifactId@'
build:
  timestamp: '@maven.build.timestamp@'
  version: '@project.version@'
spring:
  data:
    mongodb:
      port: '27017'
      database: 'poc_db'
  profiles:
    active: default
  main:
    lazy-initialization: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: 'true'
  resources:
    add-mappings: 'false'
modules:
  logging:
    logs:
      folder:
        path: ./logs
    application:
      name: '@project.artifactId@'
server:
  port: '8081'
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
